#!/bin/sh

if [ $# -lt 1 ]; then
    echo "usage: buildclient COMMIT" >&2
    exit 1
fi
set -e

tempdir="$(mktemp -d /tmp/haven.build.XXXXXX)"
cd "$tempdir"
git-archive --format=tar --remote=/srv/git/client "$1" | tar x
mkdir -p build/classes
echo "git-rev = $1" >build/classes/buildinfo
ant
cp build/haven.jar /tmp
cd /tmp
rm -rf "$tempdir"

jarsigner -storepass autosign -keystore /srv/haven/lib/jarkeys /tmp/haven.jar haven

mv -f /tmp/haven.jar /srv/haven/lib/haven.jar
